### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cxw42** [AlainPaillou/PyCuda_Denoise_Filters#1]
Thank you for publishing this code, which looks very useful!  What is the license?  I have looked in the README and source files but can't find a license statement.  Much appreciated!

-Chris White

**Comment by AlainPaillou** [comment]
Hello Chris,

This code is provided for free use (commercial or non commercial use).

The main code comes from Nvidia CUDA examples and i just made some 
adjustments to be able to use the code with classical RGB picture.

So, license is free use for everyone.

Alain

Le 2020-04-16 14:45, Chris White a écrit :

**Comment by cxw42** [comment]
Alain, thanks very much for your quick response!  I appreciate your openness and greatly enjoyed reading NVidia's [article](https://blogs.nvidia.com/blog/2019/12/23/gpu-camera-dijon/) about your work.    Best wishes!
