### ISSUE TITLE
JetsonSky

### ISSUE THREAD

**Issue by vic4hub** [AlainPaillou/PyCuda_Denoise_Filters#2]
Hey @AlainPaillou I am a hobbyist/tinkerer, I've been in touch with you via nvidia thread. I am looking for your JetsonSky repo and it looks like you've taken it down. Is there still a way for me to get a copy - I am merely trying to follow along your progress and use it w/ my camera.

**Comment by AlainPaillou** [comment]
Hello,
i have released JetsonSky in my Github. You can download it.

Alain
